### ISSUE TITLE
Unknown column 'name' in 'order clause'

### ISSUE THREAD

**Issue by weitblick** [Mark-H/VersionX2#73]
on save a resource I always get this error in error log (only in MODX 2.3.2! no problem at MODX 2.3.1 and early):
(ERROR @ /connectors/index.php) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'name' in 'order clause'
)

**Comment by intersel** [comment]
What the impact of this error? any lead to fix the problem?

**Comment by blue148** [comment]
I can verify that the error is also happening in 2.3.3. The impact is that it fills up the error log due to loggin gon each save of a resource.

**Comment by BearsFan** [comment]
Hi, I can also confirm I'm seeing this error on a few of my sites.  Did anyone find a fix for this?

**Comment by swbraun** [comment]
Same error here.

**Comment by sylbal** [comment]
Hi all,

Same error here, using ModX-2.3.3.

**Comment by 70hundert** [comment]
looking for a fix for this as well. MODx 2.3.3 using VersionX 2.1.0

**Comment by Mark-H** [comment]
Thanks @intersel for tracking down what query was causing the error, that was a great help in tracking this one down.

**Comment by rainbowtiger** [comment]
That fix doesn't work for me. When I install it, then try to save a document, I get the "please correct the errors in your form before submitting" message, and the Versions tab wants me to enter something into the Resource Type field, which is blank.

**Comment by indygfx** [comment]
The same behavior in my installation "please correct the errors in your form before submitting". So the fix doesn’t work. We are running modx vers. 2.3.3-pl

**Comment by Mark-H** [comment]
@indygfx (and @rainbowtiger), that is a different bug #78 that was fixed in VersionX 2.1.2. Make sure you're on that version.

**Comment by BearsFan** [comment]
Hi Mark, I have updated VersionX to the latest/confirmed that the fix above is in/, but I'm still getting that error when I save a resource....I have cleared cache, is there anything else to do post upgrade?
